POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Anna",
    "password": "salasana"
}

###
//wrong login 

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Anna Vääränimi",
    "password": "salasana"
}
